[mssql]
  dbname  = "TIS_FinanzasGlobal"
  host    = "10.102.192.42"
  port	  = "1433"
  user    = "Rafal"
  pass    = "Rfl2206"
  sslmode="disable"

  blacklist = ["RRHH_cmb_organization", "tblAccounting", "tblLog", "tblLogBulkOps", "tblLogFunnel", "tblLogProjects", "tmpAccounting", "tmpTable",
  "RRHH_cmb_jobRoles","RRHH_cmb_mancomunado","RRHH_employees","RRHH_cmb_prlJobCategories","RRHH_salaryFinanciera_encrypted","RRHH_cmb_prlJobCategoriesToPositionsMap","RRHH_cmb_pensionPlans","RRHH_salaryExcludedEmployees","RRHH_cmb_atamPercent","RRHH_healthInsurance","RRHH_cmb_prlJobPositions","RRHH_cmb_organization","RRHH_accidentInsurance","RRHH_cmb_recruitmentChannels","RRHH_lifeInsurance","RRHH_cmb_shiftTypes","RRHH_cmb_shareIssues","RRHH_shares","RRHH_config_calcTrialPeriod","RRHH_kmAndDietasExpenditures","RRHH_cmb_nationalities","RRHH_guardias_trabajosExtra","RRHH_personalData","RRHH_foodVouchers","RRHH_cmb_numSegSocialEmpresa","RRHH_cmb_conceptosMeta4","RRHH_config_TF_GID_Map","RRHH_cmb_contractModelsAndTypes","RRHH_sharesPurchases","RRHH_cmb_bankEntities","RRHH_objectiveBonuses","RRHH_config_meta4Mapping","RRHH_socialBenefits","RRHH_socialFunds","RRHH_config_meta4ConfigNames","RRHH_trainingExpenses","RRHH_salaryFinanciera","RRHH_followers","RRHH_cmb_costsProfiles","RRHH_cmb_educationClassificationTypes","RRHH_salaries","RRHH_cmb_Sexes","RRHH_cmb_employeeStatusTypes","RRHH_cmb_employeeTypes","RRHH_prlData","RRHH_cmb_expenditureTypes","RRHH_employeeContracts","RRHH_cmb_Iso27001_profiles","RRHH_cmb_gradings","RRHH_receptionChecks","RRHH_cmb_convenioLevelsAndSubGroups","RRHH_cmb_jobCenters","RRHH_blogPosts",
  # "tblFunnelOfertas","tblFunnelOfertasEstimacion","tblFunnelOfertasEstimacionShadow","tblFunnelRF","tblFunnelRFShadow",
  "tblRollingForecastShadow"]

[aliases.tables.accounting_financial_statements]
  down_plural   = "accounting_FinancialStatements"
  down_singular = "accounting_FinancialStatement"


# [aliases.tables.tbl_funnel_ofertas]
#   up_plural   = "TblFunnelOfertas"
#   up_singular = "TblFunnelOferta"
#   down_plural   = "tblFunnelOfertas"
#   down_singular = "tblFunnelOferta"

# [aliases.tables.tbl_countries_esp]
#   down_plural   = "tblCountriesEsp"
#   down_singular = "tblCountryEsp"

# [aliases.tables.tbl_funnel_ofertas_estimacion]
#   down_plural   = "tblFunnelOfertasEstimacion"
#   down_singular = "tblFunnelOfertEstimacion"
  
# [aliases.tables.tbl_funnel_ofertas_estimacion.relationships.FK_tblFunnelOfertasEstimacion_tblFunnelOfertas]
#   local = "tbl_funnel_offs_estim"
#   foreign = "tbl_funnel_ofertas"
